apiVersion: apps/v1
kind: Deployment
metadata:
  name: handson-aspnetcore-kubernetes-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: handson-aspnetcore-kubernetes-app
  template:
    metadata:
      labels:
        app: handson-aspnetcore-kubernetes-app
    spec:
      containers:
      - name: handson-aspnetcore-kubernetes-container
        image: handson.aspnetcore.kubernetes:1.0.1
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name